spring:
    application:
        name: zuul-service
server:
    port: 6060
eureka:
    client:
        serviceUrl:
            defaultZone: http://10.64.140.215:8969/eureka/
zuul:
    routes:
        rest-service:
            path: /rest/**
#            serviceId: rest-service
            url: http://rest-service:7070

    ratelimit:
        #    key-prefix: springcloud-book #按粒度拆分的临时变量key前缀
        enabled: true #启用开关
        #    repository: IN_MEMORY #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式
        #    behind-proxy: true #表示代理之后
        default-policy: #全局限流策略，可单独细化到服务粒度
            limit: 100 #在一个单位时间窗口的请求数量
            #      quota: 0 #在一个单位时间窗口的请求时间限制
            refresh-interval: 1 #单位时间窗口
            type:
                #        - user #可指定用户粒度
                #        - origin #可指定客户端地址粒度
                - url #可指定url粒度