spring:
    application:
        name: zuul-service
server:
    port: 6060
eureka:
    client:
        serviceUrl:
            defaultZone: http://10.64.140.215:8969/eureka/
zuul:
    routes:
        rest-service:
            path: /rest/**
            url: http://rest-service:7070

    ratelimit:
        enabled: true
        default-policy:
            limit: 100
            refresh-interval: 1
            type:
                - url

management:
    metrics:
        export:
            prometheus:
                enabled: true
                step: 1m
                descriptions: true
    endpoints:
        web:
            exposure:
                include: '*'