apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zuul-service
  name: zuul-service
  namespace: cn202009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-service
  template:
    metadata:
      labels:
        app: zuul-service
    spec:
      containers:
      - image: harbor.edu.cn/cn202009/zuul-service:{VERSION}
        imagePullPolicy: IfNotPresent
        name: zuul-service
        ports:
        - containerPort: 6060
      restartPolicy: Always
      imagePullSecrets:
      - name: mytoken
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-service
  name: zuul-service
  namespace: cn202009
spec:
  ports:
  - name: tcp
    nodePort: 32573
    port: 6060
    protocol: TCP
    targetPort: 7070
  selector:
    app: zuul-service
  type: NodePort
