apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zuul-service
  name: zuul-service
  namespace: cn202009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/prot: "6060"
        prometheus.io/scheme: http
        prometheus.io/path: /actuator/prometheus
      labels:
        app: zuul-service
    spec:
      containers:
      - image: harbor.edu.cn/cn202009/zuul-service:{VERSION}
        imagePullPolicy: IfNotPresent
        name: zuul-service
        ports:
        - containerPort: 6060
      restartPolicy: Always
      imagePullSecrets:
      - name: mytoken
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-service
  name: zuul-service
  namespace: cn202009
spec:
  ports:
  - name: tcp
    nodePort: 32573
    port: 6060
    protocol: TCP
    targetPort: 6060
  selector:
    app: zuul-service
  type: NodePort

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: zuul-service
  name: zuul-service
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: zuul-service
  namespaceSelector:
    matchNames:
      - default
